FROM eclipse-temurin:17-jdk-jammy

WORKDIR /app

COPY gradlew .
COPY gradle gradle
COPY build.gradle .
COPY settings.gradle .
COPY src src

RUN chmod +x gradlew

RUN ./gradlew clean build -x test

CMD ["java", "-jar", "build/libs/discodeit-0.0.1-SNAPSHOT.jar", "--server.port=${PORT}"]