# http { 를 지우세요.
resolver 127.0.0.11 valid=5s;

upstream backend_servers {
    ip_hash;
    server app:80;
}

server {
    listen 80;

    location ~ ^/(api|ws)/ {
        proxy_pass http://backend_servers;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
# 맨 끝의 } 도 지우세요.dock