[phases.setup]
nixPkgs = ["jdk17"]

[phases.build]
cmds = [
    "cd discodeit && chmod +x gradlew && ./gradlew build -x test",
    "cp $(find discodeit/build/libs -name \"*.jar\" ! -name \"*plain*\") server.jar"
]

[start]
cmd = "java -Dserver.port=${PORT:-8080} -jar server.jar"