[phases.setup]
nixPkgs = ["jdk17"]

[phases.build]
cmds = [
    "cd discodeit && chmod +x gradlew && ./gradlew build -x test",
    "cp $(ls discodeit/build/libs/*.jar | grep -v plain) ./app.jar"
]

[start]
cmd = "java -Dserver.address=0.0.0.0 -Dserver.port=${PORT:-8080} -jar app.jar"