# application-dev.yaml
server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:discodeit;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    username: sa
    password:
    driver-class-name: org.h2.Driver
  
  h2:
    console:
      enabled: true   # H2 콘솔 웹UI 사용하고 싶으면

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect