spring.application.name=discodeit
spring.profiles.active=jcf
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.boot.autoconfigure.web=DEBUG
server.port=${PORT:8080}

# ==============================
# PostgreSQL
# ==============================
spring.datasource.url=jdbc:postgresql://localhost:5432/discodeit
spring.datasource.username=discodeit_user
spring.datasource.password=discodeit1234
spring.datasource.driver-class-name=org.postgresql.Driver

# ==============================
# JPA
# ==============================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

# ==============================
# SQL
# ==============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# ==============================
# Storage
# ==============================
discodeit.storage.type=local
discodeit.storage.local.root-path=./uploads