spring:
  application:
    name: discodeit

  boot:
    admin:
      client:
        instance:
          name: discodeit

  profiles:
    active: dev

  output:
    ansi:
      enabled: always

  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 30MB

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

discodeit:
  storage:
    type: local
    local:
      root-path: .discodeit/storage

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, loggers

  info:
    env:
      enabled: true

info:
  app:
    name: Discodeit
    version: 1.7.0
    java-version: 17
    spring-boot-version: 3.4.0

  datasource:
    url: ${spring.datasource.url}
    driver-class-name: org.postgresql.Driver

  jpa:
    ddl-auto: ${spring.jpa.hibernate.ddl-auto}

  storage:
    type: ${discodeit.storage.type}
    path: ${discodeit.storage.local.root-path}

  multipart:
    max-file-size: ${spring.servlet.multipart.maxFileSize}
    max-request-size: ${spring.servlet.multipart.maxRequestSize}