spring:
  profiles:
    active: dev # 아무 설정 안 하면 기본적으로 dev를 쓰겠다는 뜻
  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 100

logging:
  level:
    com.example: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} %highlight(%-5level) %cyan([%thread]) %yellow(%logger{36}) - %msg%n"