server:
  port: ${SERVER_PORT:80}


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  boot:
    admin:
      client:
        url: ${SPRING_BOOT_ADMIN_CLIENT_URL}
        instance:
          name: discodeit
  
  
  jpa:
    hibernate:
      ddl-auto: none
      open-in-view: false

    show-sql: false
    defer-datasource-initialization: true

    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    com.example: info
    org.springframework.web: info
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql: TRACE
  file:
    path: ./.logs
    max-history: 30
    max-size: 10MB
  pattern:
    console: "%d{yy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [%X{requestId} | %X{method} | %X{requestUrl}] - %msg%n"
    file: "%d{yy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [%X{requestId} | %X{method} | %X{requestUrl}] - %msg%n"

discodeit:
  storage:
    type: local  # 이 부분이 없거나 틀리면 @ConditionalOnProperty가 이 빈을 죽입니다.
    local:
      root-path: ./storage # @Value 주입을 위해서도 필요함