plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.10'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.sprint.mission'
version = '0.0.1-SNAPSHOT'
description = 'Spring Discodeit Project'

/*java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
*/


sourceCompatibility = '17'

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    // 🌟 아래 두 줄을 추가하세요!
    // Swagger UI (springdoc-openapi) 추가
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.5'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa' // JPA & 트랜잭션 핵심
    runtimeOnly 'com.h2database:h2' // 연습용 인메모리 DB (C++의 로컬 캐시 같은 역할)

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}

tasks.register('forceCopyResources', Copy) {
    from 'src/main/resources/static'
    into 'build/resources/main/static'
}