server {

    listen 80;

    location ^~ /api/sse {

        proxy_pass http://backend_cluster;

        proxy_http_version 1.1;

        proxy_buffering off;

        proxy_cache off;

        proxy_set_header Connection '';

        add_header X-Upstream-Server $upstream_addr;
    }

    location ^~ /api/ {

        proxy_pass http://backend_cluster;

        add_header X-Upstream-Server $upstream_addr;
    }

    location ^~ /ws/ {

        proxy_pass http://backend_cluster;

        proxy_http_version 1.1;

        proxy_set_header Upgrade $http_upgrade;

        proxy_set_header Connection "upgrade";

        add_header X-Upstream-Server $upstream_addr;
    }

    location / {

        root /usr/share/nginx/html;

        try_files $uri /index.html;
    }
}