spring:
  application:
    name: discodeit
  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 30MB

discodeit:
  repository:
    type: file   # jcf | file
    file-directory: .discodeit

server:
  port: ${PORT:8080}