spring:
  boot:
    admin:
      client:
        url: ${SPRING_BOOT_ADMIN_CLIENT_URL}
  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

server:
  port: ${PORT:8080}