spring:
  boot:
    admin:
      client:
        url: http://localhost:9090
  datasource:
    url: jdbc:h2:mem:dividends;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

logging:
  level:
    root: debug

springdoc:
  swagger-ui:
    path: /swagger-ui.html  # 접속 경로 설정
    groups-order: DESC
  api-docs:
    path: /api-docs

info:
  app:
    name: Discodeit
    version: 1.7.0
    java-version: 17
    spring-boot-version: 3.4.0
  config:
    datasource:
      url: ${spring.datasource.url}
      driver-class-name: ${spring.datasource.driver-class-name}
    jpa:
      ddl-auto: ${spring.jpa.hibernate.ddl-auto}
    storage:
      type: ${storage.type:local}
      path: ${storage.path:/tmp}
    multipart:
      max-file-size: ${spring.servlet.multipart.max-file-size}
      max-request-size: ${spring.servlet.multipart.max-request-size}

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,loggers"