discodeit:
  storage:
    local:
      root-path: ./build/test-storage

spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    driver-class-name: org.h2.Driver
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: create-drop # 테스트 시작 시 생성, 종료 시 삭제
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: never # data.sql 등이 있다면 방지

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE # 파라미터 확인용