spring:
  profiles:
    active: dev
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        highlight_sql: true
        use_sql_comments: true



discodeit:
  repository:
    type: jpa
    file-directory: .discodeit
  storage:
    type: local
    local:
      root-path: ./data/storage