spring:
  application:
    name: discodeit
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  profiles:
    active: dev

logging:
  level:
    root: INFO

discodeit:
  repository:
    type: file
  storage:
    type: local