name: Java CI with Gradle

on:
  push:
    branches: [ "main", "release" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SPRING_PROFILES_ACTIVE: test
      # 깃허브 시크릿에서 가져온 AWS 정보들입니다.
      AWS_S3_ACCESS_KEY: ${{ secrets.AWS_S3_ACCESS_KEY }}
      AWS_S3_SECRET_KEY: ${{ secrets.AWS_S3_SECRET_KEY }}
      AWS_S3_REGION: ${{ secrets.AWS_S3_REGION }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      AWS_S3_PRESIGNED_URL_EXPIRATION: 600

    defaults:
      run:
        working-directory: ./discodeit

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test with Gradle
        # S3 관련 테스트(44개 중 실패했던 3개)를 포함한 모든 테스트를 실행합니다.
        run: ./gradlew test